[package]
name = "reed-solomon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
itertools = "0.14.0"
rand = "0.9.2"
reed-solomon-simd = "3.0.1"
serde = { version = "1.0.219", features = ["derive"] }
